name: Noir

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3
    - name: Install Noir toolchain
      uses: noir-lang/noirup@v0.1.3
      with:
        toolchain: nightly
    - name: Execute single SMT OP circuit
      run: |
        cd circuits/single_smt_op
        nargo execute
    - name: Execute batch SMT OP circuit
      run: |
        cd circuits/batch_smt_op
        nargo execute
